name: Suggested Addition to this Repository
description: Suggest an addition or improvement to this repository.
title: "[Repo Idea Suggestion]: "
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see added or improved?
      description: Briefly describe your suggestion.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Additional Context (Optional)
      description: Include any example code, links, or references if helpful.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        @BrownEpiHSR/a-team-biostatisticians will review and coordinate next steps.
